-- Create USER_INFO table for authentication
CREATE TABLE public.USER_INFO (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  USER_NAME TEXT NOT NULL UNIQUE,
  USER_PASS TEXT NOT NULL,
  NAME TEXT NOT NULL,
  LNAME TEXT NOT NULL,
  NICK_NAME TEXT,
  EMAIL TEXT NOT NULL UNIQUE,
  CREATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UPDATE_BY TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create EMPLOYEE table
CREATE TABLE public.EMPLOYEE (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  COMPANY_NM TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  EMP_ID TEXT NOT NULL UNIQUE,
  EMP_NAME TEXT NOT NULL,
  EMP_LNAME TEXT NOT NULL,
  NICK_NAME TEXT,
  IDENTIFY_NUMBER TEXT,
  POSITION_NM TEXT,
  DEPARTMENT_NM TEXT,
  START_WORKING_DATE DATE,
  BASE_SALARY DECIMAL(15,2) DEFAULT 0,
  BANK_NAME TEXT,
  BANK_ACC_NUMBER TEXT,
  BANK_ACC_NAME TEXT,
  CREATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UPDATE_BY TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create SALARY_DETAIL table
CREATE TABLE public.SALARY_DETAIL (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  EMP_ID TEXT NOT NULL REFERENCES public.EMPLOYEE(EMP_ID) ON DELETE CASCADE,
  COMPANY_NM TEXT,
  EMP_NAME TEXT,
  EMP_LNAME TEXT,
  NICK_NAME TEXT,
  BASE_SALARY DECIMAL(15,2) DEFAULT 0,
  OT_TIME DECIMAL(10,2) DEFAULT 0,
  OT_AMT DECIMAL(15,2) DEFAULT 0,
  ALLOWANCE_AMT DECIMAL(15,2) DEFAULT 0,
  BONUS_AMT DECIMAL(15,2) DEFAULT 0,
  SSO_AMT DECIMAL(15,2) DEFAULT 0,
  WHT_AMT DECIMAL(15,2) DEFAULT 0,
  STUDENT_LOAN DECIMAL(15,2) DEFAULT 0,
  DEDUCTION DECIMAL(15,2) DEFAULT 0,
  NET_PAYMENT DECIMAL(15,2) DEFAULT 0,
  TRANSFER_DATE DATE,
  BANK_NAME TEXT,
  BANK_ACC_NUMBER TEXT,
  BANK_ACC_NAME TEXT,
  DEPARTMENT_NM TEXT,
  EMAIL TEXT,
  CREATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UPDATE_BY TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.USER_INFO ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.EMPLOYEE ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.SALARY_DETAIL ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Allow all for authenticated users" ON public.USER_INFO FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON public.EMPLOYEE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated users" ON public.SALARY_DETAIL FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Allow public read on USER_INFO for login
CREATE POLICY "Allow public read for login" ON public.USER_INFO FOR SELECT TO anon USING (true);

-- Create UPDATE_BY trigger function
CREATE OR REPLACE FUNCTION public.update_UPDATE_BY_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.UPDATE_BY = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create triggers
CREATE TRIGGER update_user_info_UPDATE_BY BEFORE UPDATE ON public.USER_INFO FOR EACH ROW EXECUTE FUNCTION public.update_UPDATE_BY_column();
CREATE TRIGGER update_employee_UPDATE_BY BEFORE UPDATE ON public.EMPLOYEE FOR EACH ROW EXECUTE FUNCTION public.update_UPDATE_BY_column();
CREATE TRIGGER update_SALARY_DETAIL_UPDATE_BY BEFORE UPDATE ON public.SALARY_DETAIL FOR EACH ROW EXECUTE FUNCTION public.update_UPDATE_BY_column();